server.port=8083
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=identity
eureka.client.service-url.defaultZone=${EUREKA_SERVER}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{36}){cyan} %clr(:){faint} %m%n
logging.level.root=INFO
logging.level.com.atlantabanking.identity=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO
logging.level.com.netflix.discovery=INFO
logging.level.com.netflix.eureka=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
eureka.client.enabled=false