spring.application.name=identity-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
info.app.name=Atlanta Banking Identity Service
info.app.version=1.0.0
info.app.description=Identity and Authentication Microservice
info.app.team=Atlanta Banking Backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=identity
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
jwt.expiration=86400000