spring.application.name=identity-service
spring.profiles.active=dev
info.app.name=Atlanta Banking Identity Service
info.app.version=1.0.0
info.app.description=Identity and Authentication Microservice
info.app.team=Atlanta Banking Backend