server:
  port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/audit_test}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

    properties:
      hibernate:
        default_schema: audit

eureka:
  client:
    enabled: false

jwt:
  secret: TestSecretKeyForJUnitOnly

logging:
  level:
    root: WARN